spring.application.name=menu-service
spring.config.import=optional:configserver:http://localhost:8888

# Port Configuration
server.port=8081

# MongoDB Connection (Docker Container - Port 27017)
spring.data.mongodb.uri=mongodb://localhost:27017/bytebites_menu

# Eureka Client Setup
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true